/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MarketIndexImport } from './routes/market/index'
import { Route as IndexIndexImport } from './routes/index/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as MarketStockIndexImport } from './routes/market/stock/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MarketIndexRoute = MarketIndexImport.update({
  path: '/market/',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/index/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const MarketStockIndexRoute = MarketStockIndexImport.update({
  path: '/market/stock/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/index/': {
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof rootRoute
    }
    '/market/': {
      preLoaderRoute: typeof MarketIndexImport
      parentRoute: typeof rootRoute
    }
    '/market/stock/': {
      preLoaderRoute: typeof MarketStockIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutIndexRoute,
  BlogIndexRoute,
  IndexIndexRoute,
  MarketIndexRoute,
  MarketStockIndexRoute,
])

/* prettier-ignore-end */
